<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderTableSeeder extends Seeder
{

    public function run()
    {
        DB::table('orders')->insert([
        	[
        		'user_id'=>2,
        		'total_price'=>500000,
        		'invoice_number'=>'A0021',
        		'status'=>'SUBMIT'
        	],
        	[
        		'user_id'=>1,
        		'total_price'=>450000,
        		'invoice_number'=>'A0123',
        		'status'=>'SUBMIT'
        	],
        	[
        		'user_id'=>3,
        		'total_price'=>650500,
        		'invoice_number'=>'A0101',
        		'status'=>'PROCESS'
        	],
        	[
        		'user_id'=>5,
        		'total_price'=>330000,
        		'invoice_number'=>'B0033',
        		'status'=>'FINISH'
        	],
        	[
        		'user_id'=>4,
        		'total_price'=>405000,
        		'invoice_number'=>'C0B22',
        		'status'=>'CANCEL'
        	],
        	[
        		'user_id'=>1,
        		'total_price'=>150000,
        		'invoice_number'=>'A0111',
        		'status'=>'SUBMIT'
        	],
        	[
        		'user_id'=>6,
        		'total_price'=>410050,
        		'invoice_number'=>'AC022',
        		'status'=>'PROCESS'
        	],
        	[
        		'user_id'=>8,
        		'total_price'=>765000,
        		'invoice_number'=>'AA041',
        		'status'=>'FINISH'
        	],
        	[
        		'user_id'=>4,
        		'total_price'=>220500,
        		'invoice_number'=>'A0231',
        		'status'=>'CANCEL'
        	],
        	[
        		'user_id'=>2,
        		'total_price'=>304001,
        		'invoice_number'=>'AA011',
        		'status'=>'SUBMIT'
        	],
        	[
        		'user_id'=>5,
        		'total_price'=>110000,
        		'invoice_number'=>'B0221',
        		'status'=>'PROCESS'
        	],
        	[
        		'user_id'=>6,
        		'total_price'=>105000,
        		'invoice_number'=>'A1081',
        		'status'=>'PROCESS'
        	],
        	[
        		'user_id'=>1,
        		'total_price'=>602000,
        		'invoice_number'=>'D0511',
        		'status'=>'FINISH'
        	],
        	[
        		'user_id'=>4,
        		'total_price'=>710000,
        		'invoice_number'=>'A1121',
        		'status'=>'SUBMIT'
        	],
        	[
        		'user_id'=>7,
        		'total_price'=>415000,
        		'invoice_number'=>'C0322',
        		'status'=>'CANCEL'
        	],
        ]);
    }
}
